import type { Diagnostic } from './diagnostics.js';
import type { GeneratedProject } from './generator.js';
import { classifyChange, type ChangeStatus } from './diff.js';
import { contentHash } from './hash.js';

// The universal file-level upgrade engine. Both generators regenerate from a
// stored definition, then diff the fresh output against what's on disk using ONE
// vocabulary — so a host consumes the same plan whatever the language. Structured
// manifest diffs (package.json / pyproject.toml) are attached by the owning
// generator via `plan.manifest`; core never parses a manifest.

/** The full per-file upgrade vocabulary: the four "differs" cases from
 *  {@link classifyChange} plus the three the caller resolves by presence/equality. */
export type UpgradeFileStatus =
	'unchanged' | 'new-generated' | 'removed-from-template' | ChangeStatus;

export interface UpgradeFileChange {
	path: string;
	status: UpgradeFileStatus;
	/** True only when applying the freshly-generated content is safe (the user
	 *  hadn't diverged): `new-generated` or `template-only-change`. */
	safeToApply: boolean;
	reason: string;
}

export interface FileUpgradePlan {
	files: UpgradeFileChange[];
	baselineAvailable: boolean;
	/** Generator-specific structured manifest diff, opaque to core. */
	manifest?: unknown;
}

/** Compute the universal file-level upgrade plan and the safe-to-apply patch.
 *  `baselineFileHashes` is the scaffold-time baseline (path → content hash); without
 *  it, any on-disk divergence is reported as an ambiguous `changed` (not auto-applied). */
export function computeProjectUpgrade(input: {
	generatedFiles: Record<string, string>;
	currentFiles: Record<string, string | undefined>;
	baselineFileHashes?: Record<string, { hash: string }>;
}): { plan: FileUpgradePlan; patch: Record<string, string> } {
	const { generatedFiles, currentFiles, baselineFileHashes } = input;
	const baselineAvailable = !!baselineFileHashes && Object.keys(baselineFileHashes).length > 0;
	const files: UpgradeFileChange[] = [];
	const patch: Record<string, string> = {};

	for (const [path, generated] of Object.entries(generatedFiles).sort(([a], [b]) =>
		a.localeCompare(b),
	)) {
		const current = currentFiles[path];
		if (current === undefined) {
			files.push({
				path,
				status: 'new-generated',
				safeToApply: true,
				reason: 'newly generated by the current template',
			});
			patch[path] = generated;
		} else if (current === generated) {
			files.push({
				path,
				status: 'unchanged',
				safeToApply: false,
				reason: 'already matches the current template',
			});
		} else {
			const baseHash = baselineFileHashes?.[path]?.hash;
			const c = classifyChange({
				hasBaseline: baseHash !== undefined,
				currentEqualsBaseline: contentHash(current) === baseHash,
				generatedEqualsBaseline: contentHash(generated) === baseHash,
			});
			files.push({ path, status: c.status, safeToApply: c.safeToApply, reason: c.reason });
			if (c.safeToApply) patch[path] = generated;
		}
	}

	// A baseline file the current template no longer generates. Removal is always a
	// host decision, never auto-applied.
	if (baselineFileHashes) {
		for (const path of Object.keys(baselineFileHashes).sort()) {
			if (!(path in generatedFiles)) {
				files.push({
					path,
					status: 'removed-from-template',
					safeToApply: false,
					reason: 'the template no longer generates this file',
				});
			}
		}
	}

	return { plan: { files, baselineAvailable }, patch };
}

export function summarizeFileUpgrade(plan: FileUpgradePlan): {
	safeChanges: number;
	conflicts: number;
} {
	let safeChanges = 0;
	let conflicts = 0;
	for (const f of plan.files) {
		if (f.safeToApply) safeChanges++;
		else if (f.status === 'both-changed' || f.status === 'changed') conflicts++;
	}
	return { safeChanges, conflicts };
}

// ---- the common upgrade-result envelope ------------------------------------

export interface UpgradeMetadata {
	fromVersion?: string;
	toVersion?: string;
	baselineAvailable: boolean;
	hasConflicts: boolean;
	hasSafeChanges: boolean;
	[key: string]: unknown;
}

/** The envelope every generator's `upgradeProject` returns, so a host consumes an
 *  upgrade the same way regardless of language. `plan.manifest` carries the
 *  generator's own structured manifest diff. */
export interface UpgradeResult {
	generatedProject: GeneratedProject;
	plan: FileUpgradePlan;
	patch: Record<string, string>;
	diagnostics: Diagnostic[];
	metadata: UpgradeMetadata;
}
